import type { Metadata } from "next";
import {
  DM_Mono,
  Geist,
  Geist_Mono,
  Spline_Sans,
  STIX_Two_Text,
} from "next/font/google";
import "../styles/globals.css";
import { Providers } from "@/redux/Providers";
import { Toaster } from "react-hot-toast";
import ApplicationComp from "@/components/ApplicationComp";
import ApplicationDetails from "@/components/ApplicationDetails";
import ProfileModal from "@/components/ProfileModal ";
import AdminDashboard from "@/components/AdminDashboard";

const dmMono = DM_Mono({
  weight: ["400", "500"],
  variable: "--font-dm-mono",
  subsets: ["latin"],
});

const stixTwoMath = STIX_Two_Text({
  weight: ["400", "700"],
  variable: "--font-stix-two-math",
  subsets: ["latin"],
});

const splineSans = Spline_Sans({
  weight: ["400", "700"],
  variable: "--font-spline-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${dmMono.variable} ${stixTwoMath.variable} ${splineSans.className} antialiased`}
      >
        {/* <ApplicationComp/> */}
        {/* <ApplicationDetails/> */}
        {/* <ProfileModal/> */}
        {/* <AdminDashboard/> */}
        <Providers>{children}</Providers>
        <Toaster
        />
      </body>
    </html>
  );
}
