import type { Metadata } from "next";
import { DM_Mono, Spline_Sans, STIX_Two_Text } from "next/font/google";
import "../styles/globals.css";
import { Providers } from "@/redux/Providers";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/user/NavBar";
import Footer from "@/components/user/Footer";
import AuthInitializer from "@/components/auth/AuthInitializer";

// Define fonts
const dmMono = DM_Mono({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap", // ensures font-display swap
});

const stixTwoText = STIX_Two_Text({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const splineSans = Spline_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmMono.className} ${stixTwoText.className} ${splineSans.className} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <AuthInitializer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
