import { Employee } from "@/types";


export const employees: Employee[] = [
  {
    _id: "65e23a3a1f7e2b001a8c7d9e",
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    employeeID: "EMP-001",
    otherDetails: "Team Lead, Marketing",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7d9f",
    name: "Bhavna Patel",
    email: "bhavna.patel@example.com",
    employeeID: "EMP-002",
    otherDetails: "Software Engineer, R&D",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da0",
    name: "Chetan Gupta",
    email: "chetan.gupta@example.com",
    employeeID: "EMP-003",
    otherDetails: "Data Analyst, Finance",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da1",
    name: "Deepika Singh",
    email: "deepika.singh@example.com",
    employeeID: "EMP-004",
    otherDetails: "UX Designer, Product",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da2",
    name: "Esha Roy",
    email: "esha.roy@example.com",
    employeeID: "EMP-005",
    otherDetails: "HR Manager, Administration",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da3",
    name: "Farhan Khan",
    email: "farhan.khan@example.com",
    employeeID: "EMP-006",
    otherDetails: "Network Administrator, IT",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da4",
    name: "Geeta Desai",
    email: "geeta.desai@example.com",
    employeeID: "EMP-007",
    otherDetails: "Project Manager, Operations",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da5",
    name: "Harish Kumar",
    email: "harish.kumar@example.com",
    employeeID: "EMP-008",
    otherDetails: "Content Writer, Communications",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da6",
    name: "Ishita Verma",
    email: "ishita.verma@example.com",
    employeeID: "EMP-009",
    otherDetails: "Business Analyst, Sales",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da7",
    name: "Jatin Mishra",
    email: "jatin.mishra@example.com",
    employeeID: "EMP-010",
    otherDetails: "Legal Counsel, Legal",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da8",
    name: "Kavita Reddy",
    email: "kavita.reddy@example.com",
    employeeID: "EMP-011",
    otherDetails: "Graphic Designer, Creative",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7da9",
    name: "Lakshman Nair",
    email: "lakshman.nair@example.com",
    employeeID: "EMP-012",
    otherDetails: "Quality Assurance, Testing",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7daa",
    name: "Monica Kapoor",
    email: "monica.kapoor@example.com",
    employeeID: "EMP-013",
    otherDetails: "Customer Support, Services",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7dab",
    name: "Nikhil Bose",
    email: "nikhil.bose@example.com",
    employeeID: "EMP-014",
    otherDetails: "System Architect, Engineering",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7dac",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    employeeID: "EMP-015",
    otherDetails: "Senior Developer, Tech",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7dad",
    name: "Rahul Saxena",
    email: "rahul.saxena@example.com",
    employeeID: "EMP-016",
    otherDetails: "Financial Analyst, Accounts",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7dae",
    name: "Sana Kapoor",
    email: "sana.kapoor@example.com",
    employeeID: "EMP-017",
    otherDetails: "Marketing Specialist, Branding",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7daf",
    name: "Tariq Khan",
    email: "tariq.khan@example.com",
    employeeID: "EMP-018",
    otherDetails: "Operations Head, Logistics",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db0",
    name: "Usha Mehra",
    email: "usha.mehra@example.com",
    employeeID: "EMP-019",
    otherDetails: "HR Recruiter, Talent Acquisition",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db1",
    name: "Varun Malhotra",
    email: "varun.malhotra@example.com",
    employeeID: "EMP-020",
    otherDetails: "Lead Architect, Planning",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db2",
    name: "Wasiq Ali",
    email: "wasiq.ali@example.com",
    employeeID: "EMP-021",
    otherDetails: "Senior QA, Testing",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db3",
    name: "Xena Paul",
    email: "xena.paul@example.com",
    employeeID: "EMP-022",
    otherDetails: "Product Manager, Strategy",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db4",
    name: "Yusuf Ansari",
    email: "yusuf.ansari@example.com",
    employeeID: "EMP-023",
    otherDetails: "Cybersecurity Analyst, Security",
  },
  {
    _id: "65e23a3a1f7e2b001a8c7db5",
    name: "Zara Singh",
    email: "zara.singh@example.com",
    employeeID: "EMP-024",
    otherDetails: "IT Support, Infrastructure",
  },
];
